name: Hello Node App To 

on:
    push:
        paths:
            - "docker/app1-hello/node"
    workflow_dispatch:

jobs:
    Build-and-Test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: SetUp Node
              uses: actions/setup-node@v6
              with:
                node-version: 21

            - name: Build and Test
              working-directory: docker/app1-hello/node
              run: |
                npm ci
                npm test

            - name: Upload Test Reports
              uses: actions/upload-artifact@v7
              with:   
                name: coverage-reports   
                path: docker/app1-hello/node/coverage